
# TODO try https://docs.docker.com/compose/environment-variables/

services:
  ansiblecontroller:
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        HOSTUSER: ${HOSTUSER}
        HOSTUID: ${HOSTUID}
        HOSTGID: ${HOSTGID}
    image: ${CONTROLLERIMAGENAME}
    container_name: ${CONTROLLERCONTAINERNAME}
    volumes:
      - ${LOCALREPOWORKSPACE}/:/workspace
      - ${SSHDIR}/:/home/${HOSTUSER}/.ssh
      # - ${HOME}/.ssh:/root/.ssh # i don't think i need this one...
      # - ${ANSIBLEDIR}/:/home/${HOSTUSER}/.ansible
      # - ${AWSCONFIGDIR}/:/home/${HOSTUSER}/.aws
