---
services:
  ansiblecontroller:
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        HOSTUSER: ${HOSTUSER}
        HOSTUID: ${HOSTUID}
        HOSTGID: ${HOSTGID}
    image: ${CONTROLLERIMAGENAME}
    container_name: ${CONTROLLERCONTAINERNAME}
    volumes:
      - ${LOCALREPOWORKSPACE}/:/workspace
      - ${SSHDIR}/:/home/${HOSTUSER}/.ssh
