version: '3'

# TODO try https://docs.docker.com/compose/environment-variables/

services:
  ansiblecontroller:
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ${CONTROLLERIMAGENAME}
    container_name: ${CONTROLLERCONTAINERNAME}
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${ANSIBLELOCALREPO}/:/ansible
      - ${SSHDIR}/:/home/${hostuser}/.ssh
      - ${ANSIBLEDIR}/:/home/${hostuser}/.ansible
      - ${AWSCONFIGDIR}/:/home/${hostuser}/.aws
