version: '3'

# TODO try https://docs.docker.com/compose/environment-variables/

services:
  ansiblecontroller:
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ansible
    volumes:
      - ${HOME}/.ssh:/root/.ssh
