---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.*
  ansible_runner:
    package_pip: ansible-runner
  galaxy: ./galaxy-requirements.yml
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
  system: bindep.txt
  python: ee-requirements.txt
  exclude:
    system:
      - openshift-clients
images:
  base_image:
    name: quay.io/rockylinux/rockylinux:8

options:
  tags:
    - ansible:latest

additional_build_steps:
#   # Commands to insert before building the base image
#   # base image: the starting point for creating a container image.
#   # It typically contains a minimal operating system and essential utilities.
#   # used all images 
#   prepend_base:
#     - RUN #echo "Commands to insert before building the base image"

#   # Commands to insert after building the base image.
#   append_base:
#     - RUN # echo "Commands to insert after building the base image."

#   # Commands to insert before building the galaxy image.
#   # galaxy image:  a container image that includes Ansible content from
#   # Ansible Galaxy. Content here is included in the final image.
#   prepend_galaxy:
#     - RUN # echo "Commands to insert before building the galaxy image."

#   # Commands to insert after building the galaxy image
#   append_galaxy:
#     - RUN # echo "Commands to insert after building the galaxy image"

#   # Commands to insert before building the builder image.
#   # builder image: a temporary container image used during
#   # the process of creating the final execution environment image
#   prepend_builder:
#     - RUN # echo "Commands to insert before building the builder image."

#   # Commands to insert after building the builder image.
  append_builder:
   - RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

#   # Commands to insert before building the final image.
#   # final image: the consistent Ansible environment that would
#   # then be pushed out to an image registry
  prepend_final:
    - COPY --from=builder /usr/local/bin/helm /usr/local/bin/helm

#   # Commands to insert after building the final image.
#   append_final:
#     - RUN # echo "Commands to insert after building the final image."
