---

name: rebuild rocky9-2.14

on:
  # schedule:
  # - cron:  '30 5 * * 0'
  workflow_dispatch:

jobs:
  ansiblebuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your collection repository
        uses: actions/checkout@v4

      - name: Setup Ansible Builder
        uses: kheeklab/ansible-builder-action
        with:
          args: |
            --no-cache --prune-images \
            --build-arg EE_BASE_IMAGE=quay.io/rockylinux/rockylinux:9 \
            --tag hooplad/ansible:rocky9-2.14

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: hooplad/ansible:rocky9-2.14
      #     file: _build/Dockerfile
