---

name: Rebuild Rocky9 Ansible 2.14

on:
  workflow_dispatch:
    inputs:
      ansible-builder-args:
        default: ""
        description: action arguments
        required: false
        type: string

      action:
        default: create
        description: Ansible builder action; create or build
        required: true
        type: string
jobs:
  ansiblebuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your collection repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python-version }}'

      - name: Create and start virtual environment
        shell: bash
        run: |
          python3 -m venv builder-venv
          source builder-venv/bin/activate
          echo "${{ github.action_path }}" >> $GITHUB_PATH
          pip install --upgrade pip

      - name: Install ansible-builder
        shell: bash
        run: |
          pip install setuptools ansible-builder

      - name: Run ansible-builder
        shell: bash
        run: |
          ansible-builder ${{ inputs.action }} ${{ inputs.ansible-builder-args }}

      - name: Debugging
        shell: bash
        run: |
          ls -alth . && pwd

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hooplad/ansible:rocky9-2.14
          file: _build/Dockerfile
