---

name: Rebuild Rocky9 Ansible 2.14

on:
  # schedule:
  # - cron:  '30 5 * * 0'
  workflow_dispatch:
    inputs:

      python-version:
        default: '3.12'
        description: Python version
        required: false
        type: string

jobs:
  build_and_push:
    name: Build and Push Rocky9 Ansible 2.14
    runs-on: ubuntu-latest
    steps:
      - name: Check out your collection repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python-version || 3.12 }}'

      - name: Create and start virtual environment
        shell: bash
        run: |
          python3 -m venv builder-venv
          source builder-venv/bin/activate
          echo "${{ github.action_path }}" >> $GITHUB_PATH
          pip install --upgrade pip

      - name: Install ansible-builder
        shell: bash
        run: |
          pip install setuptools ansible-builder

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run ansible-builder
        shell: bash
        run: |
          ./build.sh
