---

name: Testing

on:
  # schedule:
  # - cron:  '30 5 * * 0'
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:

      - name: Testing
        shell: bash
        run: |
          docker version
