---

name: Testing

on:
  workflow_dispatch:
    inputs:
      itworks:
        default: '3.12'
        description: Python version
        required: false
        type: string
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:

      - name: Testing
        shell: bash
        run: |
          ${{ inputs.itworks }}
